[package]
authors = ["吴胜 <pickjob@126.com>"]
edition = "2018"
name = "rust-starter"
version = "0.1.0"

[dependencies]
async-std = "1.6.3"
bytes = "1.0.0"
futures = "0.3.5"
log = "0.4.11"
log4rs = {version = "1.0.0", features = ["gzip"]}
rand = "0.8.2"
threadpool = "1.8.1"
tungstenite = "0.12.0"
ureq = {version = "2.0.1", features = ["json", "charset"]}

[[example]]
name = "rand"
path = "examples/frame/rand.rs"

[[example]]
name = "threadpool"
path = "examples/frame/threadpool.rs"

[[example]]
name = "tungstenite"
path = "examples/frame/tungstenite.rs"

[[example]]
name = "ureq"
path = "examples/frame/ureq.rs"

[[example]]
name = "generic-class"
path = "examples/quirks/trait-object/generic-class.rs"

[[example]]
name = "io"
path = "examples/std/io.rs"

[[example]]
name = "fn"
path = "examples/std/fn.rs"

[[example]]
name = "arc"
path = "examples/std/concurrent/arc.rs"

[[example]]
name = "barrier"
path = "examples/std/concurrent/barrier.rs"

[[example]]
name = "mpsc"
path = "examples/std/concurrent/mpsc.rs"

[[example]]
name = "mutex"
path = "examples/std/concurrent/mutex.rs"

[[example]]
name = "rwlock"
path = "examples/std/concurrent/rwlock.rs"
