[package]
name = "rust-starter"
version = "0.1.0"
authors = ["吴胜 <pickjob@126.com>"]
edition = "2018"

[dependencies]
log = "0.4.11"
log4rs = "1.0.0-alpha-1"
bytes = "0.5.6"
rand = "0.7.3"
ureq = { version = "1.4.0", features = ["json", "charset"] }
futures = "0.3.5"
async-std = "1.6.3"
